package tr.ozanbey.agricalc.webapp.service.enumtype.plantation;


public enum EnumCoefficientType {

    SOIL_BLASTING,
    DEEP_PLOW,
    SECONDARY_OPERATION,
    DRILL_PLANTING,
    BASE_FERTILIZER,
    TOP_FERTILIZER,
    LIQUID_FERTILIZER,
    ANIMAL_FERTILIZER,
    HUMIC_ACID,
    LEONARDITE,
    WORM_COMPOST,
    BIO_CONDITIONER,
    THROAT_FILLING,
    TRACTOR_TILLER,
    WEED_CONTROL,
    DRIP_IRRIGATION,
    SPRINKLER_IRRIGATION,
    SPRAY_IRRIGATION,
    FURROW_IRRIGATION,
    SURFACE_IRRIGATION,
    PIVOT_IRRIGATION,
    DRUM_IRRIGATION,
    MACHINE_SPRAYING,
    BACKPACK_SPRAYING,
    IRRIGATION_SPRAYING,
    LOADED_TRANSPORT,

    WORKING_HOURS,
    MALE_WORKER_RATIO,
    FEMALE_WORKER_RATIO,
    IRRIGATION_SPECIFIC_CONSUMPTION_CONSTANT,
    PUMP_EFFICIENCY_CONSTANT,
    MOTOR_EFFICIENCY_CONSTANT,
    CONSTANT_NUMBER,
    PUMP_MOTOR_EFFICIENCY,
    GRAVITY,
    POLE_SERVICE_LIFE,
    TRACTOR_CARRYING_CAPACITY,
    CARRYING_CAPACITY

}
